"""test

Revision ID: ec7e91f05147
Revises: 
Create Date: 2024-01-08 23:34:39.371753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec7e91f05147'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('wfm_id', sa.String(), nullable=False),
    sa.Column('url_name', sa.String(), nullable=False),
    sa.Column('tradable', sa.Boolean(), nullable=False),
    sa.Column('trading_tax', sa.Integer(), nullable=True),
    sa.Column('quantity_for_set', sa.Integer(), nullable=True),
    sa.Column('set_root', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('icon_format', sa.String(), nullable=True),
    sa.Column('thumb', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('max_rank', sa.Integer(), nullable=True),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('ducats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('url_name'),
    sa.UniqueConstraint('wfm_id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('wiki_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('platinum', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('part_of_set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('part_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('main_name', sa.String(), nullable=False),
    sa.Column('part_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('subtype', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('value_subtypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subtype', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtype')
    )
    op.create_table('value_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('value_tags')
    op.drop_table('value_subtypes')
    op.drop_table('tags')
    op.drop_table('subtypes')
    op.drop_table('part_of_set')
    op.drop_table('orders')
    op.drop_table('languages')
    op.drop_table('items')
    # ### end Alembic commands ###
